#!/bin/bash
#PBS -l walltime=00:10:00
#PBS -l mem=200Mb
#PBS -l ncpus=16
#PBS -j oe

# add modules
module purge
module add namd/3.0.1
module add tcl/8.6.12

# check if exists
[[ $PBS_O_WORKDIR ]] || { echo path does not exist; exit 1; } && cd ${PBS_O_WORKDIR}

# print info
hostname
nproc
lscpu | grep "Model name"

# run program
#PATH="/srv/scratch/z5358697/namd:$PATH" namd3 +p$(nproc) equilibrate.namd
namd3 +p$(nproc) equilibrate.namd

# print cpuinfo
echo hostname $(hostname)
echo nproc $(nproc)
lscpu | grep "Model name"
# lscpu | grep "Model name" | cut -d : -f 2 | xargs

# TODO
# submit jobs for forwards and backwards
