#cd prod_0 && qsub prod_0.sh && cd ..
cd prod_1 && qsub prod_1.sh && cd ..
cd prod_2 && qsub prod_2.sh && cd ..
cd prod_3 && qsub prod_3.sh && cd ..
cd prod_4 && qsub prod_4.sh && cd ..
cd prod_5 && qsub prod_5.sh && cd ..
cd prod_6 && qsub prod_6.sh && cd ..
cd prod_7 && qsub prod_7.sh && cd ..
cd prod_8 && qsub prod_8.sh && cd ..
cd prod_9 && qsub prod_9.sh && cd ..
cd prod_10 && qsub prod_10.sh && cd ..
cd prod_11 && qsub prod_11.sh && cd ..
cd prod_12 && qsub prod_12.sh && cd ..
cd prod_13 && qsub prod_13.sh && cd ..
cd prod_14 && qsub prod_14.sh && cd ..
cd prod_15 && qsub prod_15.sh && cd ..
cd prod_16 && qsub prod_16.sh && cd ..
cd prod_17 && qsub prod_17.sh && cd ..
cd prod_18 && qsub prod_18.sh && cd ..
cd prod_19 && qsub prod_19.sh && cd ..
