#!/usr/bin/bash
#PBS -l ngpus=1
#PBS -l walltime=01:00:00
#PBS -l mem=500Mb
#PBS -j oe
#PBS -J 0-19
set -e

cd "${PBS_O_WORKDIR}/${PBS_ARRAY_INDEX}"

PATH="/srv/scratch/z5358697/namd:$PATH" namd3 "+p$(nproc)" input.namd
