#!/usr/bin/bash
#PBS -l walltime=12:00:00
#PBS -l mem=500Mb
#PBS -l ncpus=16
#PBS -l select=cpuflags=avx512f
#PBS -j oe
#PBS -J 0-14
set -e


# check if exists
cd "${PBS_O_WORKDIR}"

echo

echo hostname "$(hostname)"
echo nproc "$(nproc)"
lscpu | grep "Model name"

PATH="/srv/scratch/z5358697/namd_avx512:$PATH" namd3 "+p$(nproc)" min.namd
PATH="/srv/scratch/z5358697/namd_avx512:$PATH" namd3 "+p$(nproc)" equil.namd
