#!/usr/bin/bash
#PBS -l walltime=12:00:00
#PBS -l mem=500Mb
#PBS -l ncpus=16
#PBS -j oe
set -e


# check if exists
cd "${PBS_O_WORKDIR}"

echo

echo hostname "$(hostname)"
echo nproc "$(nproc)"
lscpu | grep "Model name"


PATH="/srv/scratch/z5358697/namd:$PATH" namd3 "+p$(nproc)" mobley_337666_min.namd
PATH="/srv/scratch/z5358697/namd:$PATH" namd3 "+p$(nproc)" mobley_337666_equil.namd

