#!/usr/bin/bash
#PBS -l walltime=01:00:00
#PBS -l mem=500Mb
#PBS -l ncpus=16
#PBS -l ngpus=1
#PBS -j oe
#PBS -J 0-79
set -e

cd "${PBS_O_WORKDIR}/${PBS_ARRAY_INDEX}"

PATH="/srv/scratch/z5358697/namd_cuda:$PATH" namd3 "+p$(nproc)" relaxed.namd
